theme: jekyll-theme-minimal
title: Welcome to Chrisite's Homepage
description: Words and pics.
defaults:
- scope:
path: "/images"
values:
image: true

{% assign image = site.static_files | where: "image", true %}
{% for myimage in image %}
  {{ myimage.path }}
{% endfor %}

